### ISSUE TITLE
Using this template in overleaf

### ISSUE THREAD

**Issue by arilwan** [ruilvo/FCUP_Thesis_LaTeX#13]
I read in the `Front/main.tex` that the file **"Must be compiled with XeLaTex".**  Considering the fact that [overleaf](https://www.overleaf.com/) uses  `pdfLaTeX` compiler, changing it to `XeLaTeX` generates errors and warning.

Can you please explain how this could be used in overleaf? For example, some pages in the first few (preamble) are not required for my programme (MAPi).

**Comment by ruilvo** [comment]
Hello,

You _can_ change the compiler in overleaf. Now you have two options:

## How to **not** use the front pages

If you don't want the cover pages as they don't apply to you, you can just comment out L37 to L44 on `main.tex`. 

Something like:

```latex
%-------------------------------------------------------------------------
%	DOCUMENT
%-------------------------------------------------------------------------

\begin{document}

% Start counting pages in an unused scheme to fix backref
% \pagenumbering{Alph}

% Includes the front pages (cover and etc.)
% \pagestyle{empty}
% \includepdf[pages={1},pagecommand={},scale=1]{Front/main}
% \cleardoublepage
% \includepdf[pages={2},pagecommand={},scale=1]{Front/main}
\cleardoublepage
\pagestyle{fancy}
```

Not sure about commenting out the last `\cleardoublepage` and the `\pagestyle{fancy}`. Try it like this, if there's something weird, try commenting out the last `\cleardoublepage` and/or the `\pagestyle{fancy}`

You can then just delete the `/Front` directory as you won't ever need it.

## How to **use** the front pages

Now, if you want to use the nice front cover and front matter pages, you need to compile them *separately*.

What I usually recommend for people that want to use Overleaf and want to use the cover pages as per FCUP's standard is:

1. Create a **new** overleaf project and just dump the contents of `/Front` in there. 
2. Follow the usual instructions: edit `vars.tex`, change compiler to `XeLaTeX` (which Overleaf **can** do), build. 
3. Empty the `/Front` directory on your "main" thesis project.
4. Upload the previously built `main.pdf` from the front-only project into there. 

Then you can build your thesis as "normal" with `pdfLaTeX`. If you need to change anything in the cover, you need to go back to your "cover-only" project, change it there, build, download the `main.pdf` and reupload it to `/Front` in the main project.
